---
title: "How to Study for Introduction to Clinical Psychology"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE,
                      comment = "")
```

In this course, our goal is for you to learn about and understand the science of clinical psychology, its application in the real world, and the limitations and strengths of the research you read.
To succeed in this class, it is important that you think deeply about and learn to apply the knowledge from lecture and section, rather than simply memorizing it.
We have created this set of guidelines to describe studying strategies that might help you in this regard.

- **Strategy #1** – *Take good notes*.\
Taking good notes is especially important in this class.
Dr. Petersen purposefully leaves blanks in the lecture slides which necessitates note-taking during class.
It is also important to take notes during *discussion sections*.
Taking notes will not only facilitate active learning, but also will be useful when preparing for exams.

- **Strategy #2** – *Pay close attention to things talked about more than once.*\
Certain concepts will be emphasized much more than others.
If we discuss something several times, it is because it is a critical concept and we want to make sure you understand it.
Listen for themes that come up in both lecture and discussions sections.
Make sure you understand what is important about them!

- **Strategy #3** – *When you read an article or review a lecture, ask yourself: "What are the main messages Dr. Petersen wants us to hear?"*\
After attending lecture and the discussion sections, close your notes and ask yourself, “What were the main points that Dr. Petersen or the TA emphasized and what was important about them?” Similarly, after reading the assignment for discussion sections or lecture, turn the material face down and ask yourself, “What was important about this reading? What about this is relevant to lecture and section? What are the main things to learn?” If you read a research article, ask yourself “What are the main findings? What are the strengths and limitations of the study?” 

- **Strategy #4** – *Pay attention to the examples Dr. Petersen and the TAs use in lecture and section.*\
Examples will help place the different concepts into context.
Think about the different examples given in class and use them to learn how each concept can be applied.
This should give you a better understanding of what might otherwise be an abstract concept.

- **Strategy #5** – *Focus on understanding the concepts, not just memorizing the details.*\
Students are often taught to memorize facts to be successful in class.
While memorizing some facts will be helpful in this class, we really want you to understand how the facts are applied in clinical psychology.
Thus, many test questions will require that you both know the facts and understand more abstract concepts.
You will do best on exams if you go beyond memorizing and critically think about the ideas we present in lecture and discussion sections.
Compare concepts discussed in class and think about how they are similar or different.
Apply concepts to real world scenarios and think through the examples presented in class.
Put the concepts into your own words and try to teach them to someone else.
This helps you figure out what you do and don’t understand, which puts you in a better position to ask specific questions after class or in office hours.

- **Strategy #6** – *Do not leave things for last minute.*\
You will have a lot to study before you know it.
Try to keep up with the material and ask questions if you have them.

- **Strategy #7** – *Take advantage of the study questions and office hours.*\
The study questions posted on ICON are a great tool that will help you check for understanding of concepts.
Office hours are a great opportunity to ask questions and clarify doubts.
Don't be shy!
