---
title: "Course Syllabus"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE,
                      comment = "")
```

Last Updated: `r format(Sys.Date(), "%m/%d/%Y")`

# Course Title

PSY:2301 – Introduction to Clinical Psychology (Spring 2023)

# Course Meeting Time and Place {#lectureTime}

Monday & Wednesday 10:30–11:20 a.m., 100 Phillips Hall (PH)

# Course Website

http://icon.uiowa.edu

To access the course site, log into Iowa Courses Online (ICON) https://icon.uiowa.edu/index.shtml using your Hawk ID and password.

# Department

Department of Psychological and Brain Sciences: https://psychology.uiowa.edu

# Course Home

The College of Liberal Arts and Sciences (CLAS) is the home of this course, and CLAS governs the add and drop deadlines, the "second-grade only" option (SGO), academic misconduct policies, and other policies and procedures.
Other UI colleges may have different policies.

# Instructor

Professor Petersen\
Office: 175 Psychological and Brain Sciences Building (PBSB)\
E-mail: [isaac-t-petersen@uiowa.edu](mailto:isaac-t-petersen@uiowa.edu)\
Office Phone: 467-1014\
Student drop-in hours: Monday 4:20–5:20 & Thursday 2–4\
Note: I'm here to help you learn and succeed in PSY:2301.
Please come to my office hours to ask questions about course material, assignments, exams, or professional development (career-related issues), for instance.
I welcome you to discuss any concerns you might have about the class.
I am also available to meet with you by appointment, although I would appreciate your making every effort to see me during office hours.
The best way to reach me outside of class is by e-mail.

# Discussion Sections {#sections}

All discussion sections are in 53 VAN.
The day and time of the discussion section differ by section:

| Section | Day/Time                     | Instructor |
|---------|------------------------------|------------|
| A01     | Monday 8:30–9:20             | (NAME)     |
| A02     | Monday 9:30–10:20            | (NAME)     |
| A03     | Tuesday 12:30–1:20           | (NAME)     |
| A04     | Tuesday 3:30–4:20            | (NAME)     |
| A05     | Wednesday 10:30–11:20        | (NAME)     |
| A06     | Wednesday 11:30–12:20        | (NAME)     |
| A07     | Thursday 3:30–4:20           | (NAME)     |
| A08     | Thursday 4:30–5:20           | (NAME)     |
| A09     | Friday 12:30–1:20            | (NAME)     |
| A10     | Friday 1:30–2:20             | (NAME)     |

# Graduate Teaching Assistants:

[Name of TA 1]\
Office: [Insert]\
Sections: [Insert]\
Student drop-in hours: [Insert]\
E-mail: [Insert]

[Name of TA 2]\
Office: [Insert]\
Sections: [Insert]\
Student drop-in hours: [Insert]\
E-mail: [Insert]

[Name of TA 3]\
Office: [Insert]\
Sections: [Insert]\
Student drop-in hours: [Insert]\
E-mail: [Insert]

# Departmental Resources

Department of Psychology Main Office: G60 Psychological and Brain Sciences Building (335-2406)\
Coordinator of Undergraduate Studies: Professor Windschitl ([paul-windschitl@uiowa.edu](mailto:paul-windschitl@uiowa.edu); 335-3681)\
Academic Coordinator: Professor Johnson ([debra-johnson@uiowa.edu](mailto:debra-johnson@uiowa.edu); 335-0135)\
Chair of Department: Professor Blumberg ([mark-blumberg@uiowa.edu](mailto:mark-blumberg@uiowa.edu); 335-2424)

# Prerequisites

The Psychology department has a hierarchical course structure that requires students to complete certain prerequisites before taking upper-level classes.
The prerequisite for this course is Elementary Psychology (PSY:1001).

# Course Objectives

This course is designed to introduce you to the concepts and methods of the science of clinical psychology.

It has three areas of emphasis:

1. Fundamentals of Scientific Clinical Psychology
1. Evidence-Based Psychological Assessment
1. Evidence-Based Psychological Intervention

This course will provide an introduction to (a) major theoretical models and research methods in scientific clinical psychology; (b) several psychological problems that are particularly relevant to college students (depression, anxiety, and alcohol abuse); (c) the general principles underlying the construction, administration, and interpretation of evidence-based clinical assessments; and (d) empirically supported approaches to psychological intervention.
*You are urged to reconsider your decision to take this class if you are reluctant to examine these topics in a scientific manner.*

Taking this course should make you a more informed consumer of claims about contemporary clinical psychology and may assist in your evaluation of clinical psychology as a potential career goal.
This course is not designed to provide extensive information on the nature of psychological disorders (see Abnormal Psychology course) or to provide you with the skills to assess and treat psychological problems.
Some topics and movies will deal with sensitive or controversial issues such as alcoholism, depression, abuse, sexual assault, and suicide.

# Required Textbook

There isn't one.
Instead, this course will include a combination of book chapters, peer-reviewed journal articles, and popular media articles.
The source for all exam questions will be lecture, discussion, and all required readings for lectures and section, which will be provided on the course website on ICON.
The cost of textbooks has become so high that I am not comfortable requiring one for this course when I can cover the material adequately in other ways.
There also is no textbook available that covers the material as we do in class.
Attendance at lectures will be critical as a result, however.
If you miss a lecture or section, you will need to get notes from a peer, because we do not provide notes or re-present missed lecture or section material in meetings.
Once you have the notes from a peer, review them carefully on your own, then get into office hours with me or one of the TAs to address any specific questions that you have as soon as possible.
Feel free to come to office hours with me or with one of the TAs to discuss how best to study for a course without a textbook.

# Academic Honesty and Misconduct

All students in CLAS courses are expected to abide by the CLAS Code of Academic Honesty.
Academic misconduct must be reported by instructors to CLAS according to these procedures.

# Course Requirements and Policies

## Lecture/Discussion

We will meet twice weekly for lectures, at the time and location described [above](#lectureTime). 
My powerpoint presentations for each lecture will be posted no later than noon the day before a lecture.
I strongly recommend bringing these to class to take notes.
In addition, you are scheduled for weekly discussion sections.
You should feel free to ask questions during lecture, although some may need to be deferred given the size of the class and the need to complete coverage of specific material during lecture.
Questions are always welcome during office hours, during section, and via e-mail.
Please bear in mind that extensive or complex questions may not be addressable over e-mail.

## Attendance & Participation

In addition to lecture, you also have a weekly discussion section (the day and time differs based on the section, see [above](#sections)).
Section attendance and participation are mandatory and will be worth 8% of your final grade.
You must attend section, pay attention, participate verbally, and complete the required activities during section to receive any attendance and participation points, as indicated by your submission of the required written responses during section at the end of the section session.
There will be 12 discussions during the semester, and you will receive one point for submitting an appropriate written response at the end of each section, up to a maximum of 10 points (i.e., you will not receive extra credit for submitting appropriate responses for all 12 discussions).
Thus, you will not be penalized for missing two sections, although you still will be responsible for the covered material on exams, etc., and I urge you strongly to attend all sections.
This strategy is designed to facilitate my management of the excuses associated with an occasional missed section (i.e., no more than two during the semester).
If you miss a section, you can attend a different section during the same week only with the permission of the instructor of the different section, but you will not receive attendance and participation points for doing so (unless the absence is excused by the instructor).
In other words, make sure you attend and participate in at least 10 of your discussion sections this semester!!
Lecture attendance is not mandatory, but most material presented in lecture is not included in the readings.
You are responsible for and will be tested on all material presented in lectures, discussion sections, and in the required readings.
Regular attendance and good attention to lectures will improve what you get out of this class and is likely to improve your performance on the exams.

## Readings & Quizzes

Readings and other materials will be posted on ICON.
You are expected to do the readings before discussion section so you come prepared to learn and to help others learn.
You will have an online quiz on the readings to complete in ICON, on your own, before each discussion section.
The quizzes are not timed (you can spend as much time as you need on each quiz up until the deadline).
The deadline for each quiz is 30 minutes before your scheduled discussion section starts.
We will not accept late responses or multiple submissions.
Your lowest quiz score will be dropped.
We will not accept excused absences for quizzes because (a) you have a week to complete the quiz (and can submit it at any point during that week), and (b) we drop your lowest quiz score.
Each quiz will be weighted the same in the final grade.
Quiz answers will be viewable at the end of the week (i.e., after the last discussion section has taken their quiz).
Past experience has shown that in order to do well in this class, you should read the required material, participate actively in class, and go over your notes each week.
There is too much material being covered in this class to try to study only by frantic preparation immediately before exams.
Note that lecture and section will not cover all relevant material for the course; you will be expected to know the required readings for exams.

## Examinations

There will be 3 exams.
The exams will include multiple-choice questions.
Each exam will emphasize information presented for the third of the class that precedes it.
However, some integration of information across sections will be required for questions on the second and third exams.
Exam questions can come from any of the following sources: lectures, sections, or required readings.

### Missing Exams

Students are allowed to make up exams that have been missed due to illness, mandatory religious observations, official University activities, or other unavoidable circumstances.
If you know that you must be away at the time of an exam for one of these reasons, the instructor or TA must be contacted in advance to schedule a make-up exam.
At the time of the make-up exam, you must provide acceptable documentation to be eligible to take it: including documentation for any report of illness at the time of an exam; any other circumstances must be documented by the University of Iowa Absence Explanation Form and must be approved by the instructor.
To be eligible for a make-up exam, the instructor or TA must be contacted before the examination whenever possible, and you must bring an acceptable form of documentation for the excused absence to the make-up exam.

# Grading

Final grades will be assigned at the end of semester on the basis of your total percentage of points earned on exams, quizzes, and section participation, as detailed below.
Grades will be assigned on an absolute scale (criterion-referenced grading); course grades will not be curved.
No extra-credit opportunities are available for this course.
Final grades will be assigned based on the following ranges:

| Grade | Percent |
|-------|---------|
| A+    | 97–100% | 
| A     | 93–96   |
| A-    | 90–92   |
| B+    | 87–89   |
| B     | 83–86   |
| B-    | 80–82   |
| C+    | 75–79   |
| C     | 70–74   |
| C-    | 65–69   |
| D+    | 60–64   |
| D     | 55–59   |
| D-    | 50–54   |
| F     | < 50%   |

The relative importance of the different contributors to your grade is as follows:

 - 28%	Examination #1
 - 28%	Examination #2
 - 28%	Examination #3 (administered only during the class's Final Exam time slot)
 - 8% 	Discussion Attendance/Participation
 - 8% 	Reading Quizzes

# Tentative Course Outline (exam dates fixed)

## Section Notes

- There will be no sections during the first week of classes.
Sections will meet weekly beginning the second week of classes.
- Sections will not be held during the week of examinations.
Therefore, sections are cancelled on the following dates:  Monday 2/27 – Friday 3/3 and Monday 4/3 – Friday 4/7.

## Unit One

**Unit One: Fundamentals of Scientific Clinical Psychology**

| Date | Topic                                           |
|------|-------------------------------------------------|
| 1/16 | MLK Day (no class!)                             |
| 1/18 | Introduction & Contemporary Clinical Psychology |
| 1/23 | Classification and Diagnosis                    |
| 1/25 | Classification and Diagnosis                    |
| 1/30 | Research Methods in Clinical Psychology         |
| 2/1  | Research Methods in Clinical Psychology         |
| 2/6  | Mood Disorders                                  |
| 2/8  | Mood Disorders                                  |
| 2/13 | Mood Disorders                                  |
| 2/15 | Anxiety Disorders                               |
| 2/20 | Anxiety Disorders                               |
| 2/22 | Alcohol Use Disorders                           |
| 2/27 | Examination #1 (no sections this week!)         |

## Unit Two

**Unit Two: Evidence-Based Psychological Assessment and Prediction**

| Date | Topic                                          |
|------|------------------------------------------------|
| 3/1  | Overview of Assessment and Prediction          |
| 3/6  | Overview of Assessment and Prediction          |
| 3/8  | Interviewing, Observation, and Self-Monitoring |
| 3/13 | Spring Break (no class!)                       |
| 3/15 | Spring Break (no class!)                       |
| 3/20 | Interviewing, Observation, and Self-Monitoring |
| 3/22 | Intelligence Testing                           |
| 3/27 | Intelligence Testing                           |
| 3/29 | Personality Assessment                         |
| 4/3  | Personality Assessment and Wrap Up             |
| 4/5  | Examination #2 (no sections this week!)        |

## Unit Three

**Unit Three: Evidence-Based Psychological Intervention**

| Date | Topic                                           |
|------|-------------------------------------------------|
| 4/10 | Major Approaches to Intervention                |
| 4/12 | Major Approaches to Intervention                |
| 4/17 | Cognitive-Behavioral Therapy for Panic Disorder |
| 4/19 | Evaluation of Interventions                     |
| 4/24 | Evaluation of Interventions                     |
| 4/26 | Evidence-Based Treatments                       |
| 5/1  | Dissemination of Evidence-Based Treatments      |
| 5/3  | Intervention Controversies, Wrap-Up             |

# Date and Time of the Final Exam

The final examination date and time will be announced by the Registrar generally by the fifth week of classes and it will be announced on the course ICON site once it is known.
Do not plan your end of the semester travel plans until the final exam schedule is made public.
It is your responsibility to know the date, time, and place of the final exam.
According to Registrar's final exam policy, students have a maximum of two weeks after the announced final exam schedule to request a change if an exam conflict exists or if a student has more than two exams in one day (see the policy here).

# Drop Deadline for this Course

You may drop an individual course before the deadline; after this deadline you will need collegiate approval.
You can look up the drop deadline for this course here.
When you drop a course, a "W" will appear on your transcript.
The mark of "W" is a neutral mark that does not affect your GPA.
Directions for adding or dropping a course and other registration changes can be found on the Registrar's website.
Students can find policies on dropping and withdrawing here.

# Feedback about the Course

I welcome feedback at any point during the class.
If you have comments on the class or my teaching, please feel free to meet with me during office hours.

## Student Complaints

Students with a complaint about a grade or a related matter should first discuss the situation with the instructor, and finally with the Director or Chair of the school, department, or program offering the course.
Students should contact CLAS Undergraduate Programs for support when the matter is not resolved at the previous level.

# Communication: UI Email

Students are responsible for all official correspondences sent to their UI email address (uiowa.edu) and must use this address for any communication with instructors or staff in the UI community.

# College of Liberal Arts and Sciences (CLAS) Course Policies

Attendance and Absences

University regulations require that students be allowed to make up examinations which have been missed due to illness or other unavoidable circumstances.
See the section above on "Missing Exams" for the documentation necessary for an absence to be excused and to be eligible to take a make-up exam.
Students with mandatory religious obligations or UI authorized activities must discuss their absences with me or the TA as soon as possible.
Religious obligations must be communicated within the first three weeks of classes.

Exam Policies

# University Policies

Accommodations for Students with Disabilities
Basic Needs and Support for Students
Classroom Expectations
Exam Make-up Owing to Absence
Free Speech and Expression
Mental Health
Military Service Obligations
Non-discrimination
Religious Holy Days
Sexual Harassment/Misconduct and Supportive Measures
Sharing of Class Recordings

# Resources for Help

For tutoring services, see Tutor Iowa: https://tutor.uiowa.edu

Some of the topics covered in class involve problems that can be quite common among college students.
If you feel that you or someone you know may be struggling with an academic, emotional or psychological problem, the following organizations are available for assistance:

| Service                                                                    | Contact Info                                                    |
|----------------------------------------------------------------------------|-----------------------------------------------------------------|
| University of Iowa Academic Advising Center                                | 353-5700, https://advisingcenter.uiowa.edu                      |
| University Counseling Services                                             | 335-7294, http://www.uiowa.edu/ucs                              |
| Student Health Service - Mental Health                                     | 335-8394, http://studenthealth.uiowa.edu/services/psychiatry    |
| University of Iowa Hospitals and Clinics Adult Psychiatry Services Clinic  | 353-6314, http://www.uihealthcare.org/Psychiatry                |
| Seashore Clinic (in the UI Department of Psychological and Brain Sciences) | 335-2467, http://psychology.uiowa.edu/resources/seashore-clinic |
| Women's Resource and Action Center                                         | 335-1486, http://wrac.uiowa.edu                                 |
| Rape Victim Advocacy Program                                               | 319-335-6000 or 800-228-1625, http://www.uiowa.edu/~rvap        |
| Crisis Center of Johnson County                                            | 351-0140, http://www.jccrisiscenter.org/other-online-resources  |
| Mecca Services                                                             | 351-4357, http://www.meccaservices.com                          |
| Synchrony Behavioral Health Services                                       | 351-9072, http://www.synchronyservices.com/behhealth.html       |

If you or someone you know is contemplating suicide, either call the Crisis Center at 351-0140 or call 911.

# Disclaimer

This syllabus is subject to change.
Any changes will be discussed in class, via email, and/or on ICON.
